### ISSUE TITLE
Links to in order to support/sponsor you are broken or not yet implemented.

### ISSUE THREAD

**Issue by b-kaiser** [chesspecker/chesspecker#64]
### Describe the Bug

Selecting any of the buttons on https://www.chesspecker.com/sponsor does not lead to a possibility to donate to your project. Here function Bf() seems not to be implemented, yet. Similarly, https://github.com/support/chesspecker is not the page I am looking for.

### Expected Behavior

I get a possibility to sent you some money.

### To Reproduce

Visit the websites and click the buttons and links.

### What browser are you using? (if relevant)

Firefox Version 101.0.1 (64-bit) on Fedora Linux

**Comment by pnxdxt** [comment]
This is now fixed. Thanks for reporting it!

**Comment by b-kaiser** [comment]
No problem. ;-)

**Comment by b-kaiser** [comment]
@pnxdxt  https://github.com/support/chesspecker is still not the page I am looking for.
